### ISSUE TITLE
notion links in the Resources.pdf dont seem to work

### ISSUE THREAD

**Issue by boogieshafer** [PacktPublishing/ChatGPT-101---Supercharge-Your-Work-Life-with-ChatGPT#1]
the links to Notion pages in the Resources.pdf dont seem to work

**Comment by boogieshafer** [comment]
found this link under the Q&A of the udemy hosted version of this same material which seems to be the current home

https://melisai.notion.site/ChatGPT-101-Supercharge-Your-Work-Life-750-Prompts-Inc-4233ca9acf234f58a6be8781dd9988b2

https://melisai.notion.site/ChatGPT-101-Prompt-Ideas-Public-2698a98149da4a16b8537f83954a76a1

**Comment by Sonakshis** [comment]
Hi @boogieshafer 
Please refer to the following updated link:
https://melisai.notion.site/ChatGPT-101-Supercharge-Your-Work-Life-750-Prompts-Inc-4233ca9acf234f58a6be8781dd9988b2
The author has compiled all the resources into this one.
